apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-app
  name: example-app
  namespace: example-app
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: example-app
  type: ClusterIP
