apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: "node-{{ .Values.namespace }}.localhost.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.appName }}
            port:
              number: {{ .Values.port }}

# kubectl describe ingress node-example
# For any errors/events

